=== elastic/ems-file-service/schema/source.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Source",
  "description": "Elastic Map Service data source",
  "type": "object",
  "required": [
    "versions",
    "production",
    "attribution",
    "type",
    "data",
    "name",
    "humanReadableName",
    "fieldMapping",
    "weight",
    "emsFormats",
    "createdAt"
  ],
  "additionalProperties": false,
  "properties": {
    "versions": {
      "type": "string",
      "description": "Must be a semver compatible string (ex. v1, 1, 1.0.0, 1.x) or range (ex 1 - 2, ^1.0.1). See more examples at https://www.npmjs.com/package/semver. "
    },
    "production": {
      "type": "boolean",
      "description": "Whether or not the layer should be published to production"
    },
    "type": {
      "type": "string",
      "enum": ["http", "ftp", "ESRI"]
    },
    "data": {
      "type": "string"
    },
    "wikidata": {
      "type": "string",
      "description": "The Wikidata ID of the region type. Used for i18n translations."
    },
    "query": {
      "description": "Query string parameters to append to the data",
      "type": "object"
    },
    "fieldMapping": {
      "description": "Specifies map source field names or properties to elastic map service properties",
      "type": "array",
      "items": { "$ref": "#/definitions/fieldMap" }
    },
    "website": {
      "type": "string"
    },
    "compression": {
      "type": "string",
      "enum": ["zip"]
    },
    "license": {
      "oneOf": [{ "type": "string" }, { "$ref": "#/definitions/license" }]
    },
    "attribution": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/i18n-attribution"
      },
      "description": "Attribution for map data in different locales when available."
    },
    "id": {
      "description": "Manifest id number. These are used as blob file identifiers in the v1 and v2 manifests.",
      "oneOf": [{ "type": "string" }, { "type": "number" }]
    },
    "ttl": {
      "description": "Time to live (seconds) until we recache the data from the source (unused)",
      "type": "integer"
    },
    "weight": {
      "description": "Weight of layer for ordering. Larger numbers appear higher in order.",
      "type": "integer"
    },
    "name": {
      "description": "Short name for source.",
      "type": "string"
    },
    "createdAt": {
      "description": "Layer creation date in ISO 8601 format.",
      "type": "string"
    },
    "humanReadableName": {
      "description": "Localized human readable names",
      "$ref": "#/definitions/i18n"
    },
    "legacyIds": {
      "description": "Identifying names or ids used in legacy versions of EMS",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "sourceFormat": {
      "$ref": "#/definitions/format",
      "description": "GIS file format for data coming from source"
    },
    "emsFormats": {
      "description": "Array of GIS file formats exposed in the Elastic Maps Service manifest",
      "type": "array",
      "items": {
        "$ref": "#/definitions/format"
      },
      "minItems": 1,
      "contains": {
        "description": "Exactly one format must be specified as the default format to use.",
        "type": "object",
        "required": ["default"],
        "properties": {
          "default": {
            "type": "boolean",
            "enum": [true]
          }
        }
      }
    },
    "note": {
      "oneOf": [{ "type": "string" }, { "type": "object" }]
    }
  },
  "definitions": {
    "i18n-attribution": {
      "type": "object",
      "additionalProperties": false,
      "required": ["label"],
      "properties": {
        "url": {
          "$ref": "#/definitions/i18n"
        },
        "label": {
          "$ref": "#/definitions/i18n"
        }
      }
    },
    "i18n": {
      "type": "object",
      "required": ["en"],
      "additionalProperties": {
        "type": "string"
      }
    },
    "license": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "text": {
          "type": "string"
        },
        "attribution": {
          "type": "boolean"
        },
        "attribution name": {
          "type": "string"
        },
        "share-alike": {
          "type": "boolean"
        }
      }
    },
    "fieldMap": {
      "description": "Specifies type, name, source, destination, and description of a field.",
      "type": "object",
      "required": ["type", "name", "desc"],
      "properties": {
        "type": {
          "description": "Type of field.",
          "type": "string",
          "enum": ["id", "property"]
        },
        "name": {
          "type": "string",
          "description": "Name of field in vector data"
        },
        "desc": {
          "type": "string",
          "description": "Human readable field name"
        }
      }
    },
    "format": {
      "description": "GIS format such as shapefile, geojson, topojson",
      "type": "object",
      "required": [ "type", "file" ],
      "properties": {
        "default": {
          "type": "boolean",
          "description": "When choosing from multiple formats, use this layer by default"
        },
        "type": {
          "type": "string",
          "enum": [
            "geojson",
            "shapefile",
            "gdb",
            "topojson",
            "wkt"
          ]
        },
        "srs": {
          "type": "string",
          "pattern": "EPSG:[0-9]+",
          "description": "Spatial Reference System. Assumed to be EPSG:4326 if not specified."
        },
        "file": {
          "type": "string",
          "description": "File name"
        },
        "layer": {
          "description": "Specifies a layer to use from the given file if necessary",
          "oneOf": [{ "type": "integer" }, { "type": "string" }]
        },
        "meta": {
          "description": "Additional properties that can be used to describe and parse the vector file",
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "feature_collection_path": {
              "type": "string",
              "description": "For TopoJSON files, the value of the member of `objects` to be used. Refer to https://github.com/topojson/topojson-specification#215-objects"
            }
          }
        }
      }
    }
  }
}

=== elastic/ems-file-service/test/fixtures/valid-sources/duplicateIds.json
[
  {
    "versions": "2",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "mordor_regions",
    "legacyIds": [ "Mordor" ],
    "humanReadableName": {
      "en": "Mordor Regions",
      "de": "Mordor",
      "zh": "魔多"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 111111111111,
    "emsFormats": [{
      "type": "geojson",
      "file": "mordor_regions.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  },
  {
    "versions": ">=1",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "isengard_regions",
    "legacyIds": [ "Isengard" ],
    "humanReadableName": {
      "en": "Isengard Regions",
      "de": "Isengard",
      "zh": "艾辛格"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 111111111111,
    "emsFormats": [{
      "type": "geojson",
      "file": "isengard_v1.geo.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  }
]

=== elastic/ems-file-service/test/fixtures/valid-sources/sources.json
[
  {
    "versions": "1.x",
    "production": false,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "mordor_regions",
    "legacyIds": [ "Mordor" ],
    "humanReadableName": {
      "en": "Mordor Regions",
      "de": "Mordor",
      "zh": "魔多"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 111111111111,
    "emsFormats": [{
      "type": "geojson",
      "file": "mordor_v1.geo.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  },
  {
    "versions": "1 - 2",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        },
        "url": {
          "en": "https://en.wikipedia.org/wiki/The_Silmarillion"
        }
      }, {
        "label": {
          "en": "Elastic Maps Service"
        },
        "url": {
          "en": "https://www.elastic.co/elastic-maps-service"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "gondor",
    "legacyIds": [ "Gondor" ],
    "humanReadableName": {
      "en": "Gondor Kingdoms",
      "de": "Gondor",
      "zh": "魔多"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Kingdom name (English)"
      }
    ],
    "weight": 0,
    "id": 222222222222,
    "emsFormats": [{
      "type": "geojson",
      "file": "gondor_v2.geo.json",
      "default": true
    }],
    "createdAt": "1200-02-28T17:13:39.288909"
  },
  {
    "versions": ">=3",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion",
          "fr": "Le Silmarillion"
        },
        "url": {
          "en": "https://en.wikipedia.org/wiki/The_Silmarillion",
          "fr": "https://fr.wikipedia.org/wiki/Le_Silmarillion"
        }
      }, {
        "label": {
          "en": "Elastic Maps Service"
        },
        "url": {
          "en": "https://www.elastic.co/elastic-maps-service"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "gondor",
    "legacyIds": [ "Gondor", "Gondor Kingdoms" ],
    "humanReadableName": {
      "en": "Gondor Kingdoms",
      "de": "Gondor",
      "zh": "魔多"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Kingdom name (English)"
      }
    ],
    "weight": 0,
    "emsFormats": [{
      "type": "geojson",
      "file": "gondor_v3.geo.json",
      "default": true
    }],
    "createdAt": "1200-02-28T17:13:39.288909"
  },
  {
    "versions": ">=2",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "rohan",
    "legacyIds": [ "Rohan", "Rohan Kingdoms" ],
    "humanReadableName": {
      "en": "Rohan Kingdoms",
      "de": "Rohan",
      "zh": "洛汗"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Kingdom name (English)"
      }
    ],
    "weight": 0,
    "id": 444444444444,
    "emsFormats": [{
      "type": "geojson",
      "file": "rohan_v2.geo.json"
    },{
      "type": "topojson",
      "file": "rohan_v2.topo.json",
      "default": true,
      "meta": {
        "feature_collection_path": "regions"
      }
    }],
    "createdAt": "1200-02-28T17:13:39.456456"
  },
  {
    "versions": ">=2",
    "production": false,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "shire",
    "legacyIds": [ "Shire", "Shire regions", "Shire Regions" ],
    "humanReadableName": {
      "en": "Shire regions",
      "de": "Auenland",
      "zh": "夏爾"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "regex": "^Q[1-9]\\d*",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "alias": [ "(geo\\.){0,}region_name" ],
        "desc": "Region name (English)"
      },
      {
        "type": "property",
        "name": "label_ws",
        "desc": "Region name (Westron)"
      }
    ],
    "weight": 0,
    "id": 333333333333,
    "emsFormats": [{
      "type": "geojson",
      "file": "shire_v2.geo.json",
      "default": true
    }, {
      "type": "topojson",
      "file": "shire_v2.topo.json",
      "default": false
    }],
    "createdAt": "1532-12-25T18:45:32.389979"
  }
]

=== elastic/ems-file-service/test/fixtures/valid-sources/weighted-sources.json
[
  {
    "versions": ">=1",
    "production": false,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "mordor_regions",
    "humanReadableName": {
      "en": "Mordor Regions",
      "de": "Mordor",
      "zh": "魔多"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 111111111111,
    "emsFormats": [{
      "type": "geojson",
      "file": "mordor_v1.geo.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  },
  {
    "versions": ">=1",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "gondor",
    "humanReadableName": {
      "en": "Gondor Kingdoms",
      "de": "Gondor",
      "zh": "魔多"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Kingdom name (English)"
      }
    ],
    "weight": 0,
    "id": 222222222222,
    "emsFormats": [{
      "type": "geojson",
      "file": "gondor_v2.geo.json",
      "default": true
    }],
    "createdAt": "1200-02-28T17:13:39.288909"
  },
  {
    "versions": ">=1",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "rohan",
    "humanReadableName": {
      "en": "Rohan Kingdoms",
      "de": "Rohan",
      "zh": "洛汗"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Kingdom name (English)"
      }
    ],
    "weight": 1,
    "emsFormats": [{
      "type": "geojson",
      "file": "rohan_v2.geo.json",
      "default": true
    }],
    "createdAt": "1200-02-28T17:13:39.456456"
  },
  {
    "versions": ">=1",
    "production": false,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "shire",
    "humanReadableName": {
      "en": "Shire regions",
      "de": "Auenland",
      "zh": "夏爾"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Region name (English)"
      },
      {
        "type": "property",
        "name": "label_ws",
        "desc": "Region name (Westron)"
      }
    ],
    "weight": 0,
    "id": 333333333333,
    "emsFormats": [{
      "type": "geojson",
      "file": "shire_v2.geo.json",
      "default": true
    }, {
      "type": "topojson",
      "file": "shire_v2.topo.json"
    }],
    "createdAt": "1532-12-25T18:45:32.389979"
  }
]

=== elastic/ems-file-service/test/fixtures/valid-sources/duplicateNames.json
[
  {
    "versions": ">=1",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "isengard_regions",
    "legacyIds": [ "Isengard" ],
    "humanReadableName": {
      "en": "Isengard Regions",
      "de": "Isengard",
      "zh": "艾辛格"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 111111111111,
    "emsFormats": [{
      "type": "geojson",
      "file": "isengard_v1.geo.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  },
  {
    "versions": "2",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "isengard_regions",
    "legacyIds": [ "Isengard Regions" ],
    "humanReadableName": {
      "en": "Isengard",
      "de": "Isengard",
      "zh": "艾辛格"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 222222222222,
    "emsFormats": [{
      "type": "topojson",
      "file": "isengard_v2.topo.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  },
  {
    "versions": ">=6",
    "production": true,
    "attribution": [
      {
        "label": {
          "en": "The Silmarillion"
        }
      }
    ],
    "type": "http",
    "data": "http://example.com",
    "name": "isengard_regions",
    "legacyIds": [ "Isengard", "Isengard Regions" ],
    "humanReadableName": {
      "en": "Isengard",
      "de": "Isengard",
      "zh": "艾辛格"
    },
    "fieldMapping": [
      {
        "type": "id",
        "name": "wikidata",
        "desc": "Wikidata identifier"
      },
      {
        "type": "property",
        "name": "label_en",
        "desc": "Region name (English)"
      }
    ],
    "weight": 0,
    "id": 333333333333,
    "emsFormats": [{
      "type": "geojson",
      "file": "isengard_v6.geo.json",
      "default": true
    }],
    "createdAt": "1000-01-02T17:12:15.978370"
  }
]
